### ISSUE TITLE
[!] Unable to find a specification for `WLEmptyState`

### ISSUE THREAD

**Issue by boardmain** [wizeline/WLEmptyState#25]
added to podfile but unable to find it

**Comment by lojals** [comment]
Can you give us more details please?
I just did a test adding `WLEmptyState` to an empty project and it is working properly.
<img width="727" alt="Screen Shot 2019-04-24 at 9 05 44 AM" src="https://user-images.githubusercontent.com/6756995/56665845-72ce3e00-6670-11e9-82b5-72606c76bfdb.png">

**Comment by RahulKatariya** [comment]
Maybe, You need to try `pod install --repo-update`.

**Comment by alexandercg** [comment]
Closing due inactivity.
