### ISSUE TITLE
Empty state always shown if `numberOfSections` is not implemented

### ISSUE THREAD

**Issue by neokree** [wizeline/WLEmptyState#28]
**Describe the bug**
If a `UIViewController`, which implements `UITableViewDataSource` does not implement the optional method `numberOfSections`, the `UITableView` always shows the empty state, even if the `numberOfRownInSection` method return a number != 0. 

**Expected behavior**
The empty state should not be shown if the `numberOfSections` is not implemented, it should be shown if the `numberOfSections` method is implemented and returns 0. 

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS 12.2
 - Version 1.0.2

**Additional context**
The problem should be in these lines of `UITable+Extensions` file:
```
    private var numberOfItems: Int {
        var items = 0
        let numberOfSections = dataSource?.numberOfSections?(in: self) ?? 0
        for section in 0..<numberOfSections {
            items += dataSource?.tableView(self, numberOfRowsInSection: section) ?? 0
        }
        return items
    }
```
The `numberOfSections` method (as `UITableViewDataSource` protocol documentation) should default to 1 if not implemented, but with this code if numberOfSections is not implemented it defaults to 0.

**Comment by lojals** [comment]
@neokree thanks for reporting this. The [fix](https://github.com/wizeline/WLEmptyState/pull/29) will be added to our next release.
