### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by benweidig** [wizeline/WLEmptyState#45]
Hi,

it would be great if Swift package Manager would also be supported.

I've already forked it https://github.com/benweidig/WLEmptyState/commit/01783571d7cc97f9bd6369d528108a619008b436 and made the necessary changes.

I would also have create a pull request BUT Swift Package Manager doesn't support assets, so either the default image must be removed, or it must be drawn in code.

Cheers,
Ben

**Comment by Abel7x** [comment]
Hey! @benweidig on swift 5.3 and the [SE-0271](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md) proposal SPM now supports resources. When Xcode 12 and Swift 5.3 gets live this feature can now be added to the repo. :D

**Comment by lojals** [comment]
Version 3.2.0 is adding SPM support with assets.
